### ISSUE TITLE
Tips or Step by Step Guide?

### ISSUE THREAD

**Issue by MitchyBAwesome** [dalbhanj/expert-tips-for-k8s-on-aws#1]
I wonder how we turn this in to Tips, as appose to a simple step by step guide. The title is "Expert Tips", so what are the tips? 

For example, Tip #1 could be "Never deploy a Kubernetes cluster the hard way" and the cluster deployment steps then show what's involved in deploying using Kops. Or maybe we have to share some top tips about deploying using Kops. For example, choosing the right networking provider to allow you to make use of private networking topology.

**Comment by dalbhanj** [comment]
Maybe we should start with anti-pattern, specify why people end up building such, talk about pros vs cons and then mention expert tips? 

Here is nice set of decks about k8s/docker best practices: https://speakerdeck.com/thesandlord/kubernetes-best-practices

**Comment by dalbhanj** [comment]
Check out security tips and let me know how it looks. I think we should have General tips and then drill down into individual sections to go into details

https://github.com/dalbhanj/expert-tips-for-k8s-on-aws/tree/master/security

**Comment by dalbhanj** [comment]
Closing this issue as I think we have standard format in place to keep the data consistent
